Homework 2
bigseized/TinkoffCourseJava2024 pull request #2
Opened 2024-02-22 19:38 UTC by bigseized

2024-02-25 17:50 UTC, SHvatov requested changes
@bigseized оставил пару минорных комментариев. Основной, на который прошу обратить внимание - про реактивщину.

2024-02-25 17:50 UTC, SHvatov commented on scrapper/src/main/java/edu/java/ClientConfiguration.java
> +    public GitHubClient gitHubClientClass() {
Клиенты уже помечены у тебя как бины, повторно создавать их не надо.

2024-02-25 17:50 UTC, SHvatov commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +    Mono<GitHubReposDTO> fetchReposInfo(String link) {
1. Почему package-private?
2. Скажу честно - пока что в реактивщину лезть не советую. Как человек, который работает с ней последние два года, я очень настоятельно советую туда не лезть. Как говорил классик, не лезь туда, оно тебя сожрет.

2024-02-25 17:50 UTC, SHvatov commented on scrapper/src/main/java/edu/java/parsers/GitHubLinkParse.java
> +public class GitHubLinkParse {
`Util\s` в конце хорошо бы иметь. Все-таки стандарт.

2024-02-25 17:50 UTC, SHvatov commented on scrapper/src/main/java/edu/java/parsers/GitHubLinkParse.java
> +public class GitHubLinkParse {
И может это утащить в метод `fetchQuestionsInfo`? На сколько тут нужен прямо утильный класс?

2024-02-26 17:16 UTC, bigseized commented on scrapper/src/main/java/edu/java/ClientConfiguration.java
> +    public GitHubClient gitHubClientClass() {
По заданию нужен этот класс с бинами, поэтому убрал @Component c клиентов.

2024-02-28 21:25 UTC, bigseized commented on scrapper/src/main/java/edu/java/parsers/GitHubLinkParse.java
> +public class GitHubLinkParse {
Сделал общий класс для всех видов ссылок, чтобы не парсить в репозитории, но и не создавать лишних классов.

2024-02-29 19:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/ClientConfiguration.java
> +    public GitHubClient gitHubClientClass() {
Оки доки, но все же призываю вас создавать бины не руками, а черз анноташки...

2024-02-29 19:30 UTC, SHvatov approved these changes
@bigseized 👌, можно мержить.

2024-02-29 20:18 UTC, merged