Homework 3
bigseized/TinkoffCourseJava2024 pull request #3
Opened 2024-02-29 20:11 UTC by bigseized

2024-03-03 18:43 UTC, SHvatov requested changes
@bigseized оставил комментарии, посмотри их, пожалуйста. И такое чувство, будто не все протестировано. Или я не прав?)

2024-03-03 18:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/controllers/BotUpdateController.java
> +        @Valid @RequestBody LinkUpdateRequest linkUpdateRequest
Чисто на будущее - советую везде юзать `@Validated`. То же самое, только с большей областью применимости. [Пример](https://stackoverflow.com/questions/63102468/why-is-validated-required-for-validating-spring-controller-request-parameters).

2024-03-03 18:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/repository/api/scrapper/ScrapperModuleClient.java
> +public class ScrapperModuleClient {
`ScrapperClient`? Сейчас это модуль, но потом он уедет в отдельный сервис (а возможно и репку).

2024-03-03 18:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/repository/api/scrapper/ScrapperModuleClient.java
> +        this("http://localhost:8080");
Не стоит - дефолтные значения стоит хранить на уровне конфигов. Пусть лучше приложение упадет из-за отсутствия `baseUrl`, чем мы через пару дней узнаем, что на проде мы бегаем на локалхост)

2024-03-03 18:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/repository/api/scrapper/ScrapperModuleClient.java
> +            service.postTgChat(id);
Не помню, писал ли я об этом или нет - но ты точно хочешь вообще все исключения проглатывать и не давать вызывающему коду их обработать?

2024-03-03 18:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/repository/api/scrapper/ScrapperModuleService.java
> +public interface ScrapperModuleService {
Я бы назвал это `ScrapperApi`, раз его использует клиент.

2024-03-03 18:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controllers/TelegramChatsController.java
> +
ой, лишние строчки)

2024-03-03 18:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controllers/TelegramChatsController.java
> +    public void postTgChat(@Min(value = 0, message = "ID должен быть >= 0") @PathVariable long id) {
О, а тут валидация работает?

2024-03-03 18:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/exceptions/ChatAlreadyRegisteredException.java
> +public class ChatAlreadyRegisteredException extends RuntimeException {
А в чем отличие от `BotApiRequestException`? Не хочешь подумать в сторону единообразной иерархии искючений?

2024-03-03 18:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/exceptions/handler/ScrapperExceptionHandler.java
> +    public ApiErrorResponse chatNotFound(ChatNotFoundException exception) {
Вот про это я и говорю - почему бы этот маппинг в `ApiErrorResponse` не унести в класс-исключение?

2024-03-03 18:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/services/chat/DeleteTelegramChatService.java
> +        if (id == HttpStatus.NOT_FOUND.value()) {
Может лучше замокирвать данные через ин мемори стейт? Типа сделать моки для репозиториев, которые заранее наполнять известными данными?

2024-03-03 23:27 UTC, bigseized commented on scrapper/src/main/java/edu/java/controllers/TelegramChatsController.java
> +    public void postTgChat(@Min(value = 0, message = "ID должен быть >= 0") @PathVariable long id) {
В этом тесте проверяю:
![image](https://github.com/bigseized/TinkoffCourseJava2024/assets/91249122/ed0a2865-7811-487e-ae01-4774192c02e4)

2024-03-11 20:14 UTC, SHvatov approved these changes
🔥, 🚀

2024-03-11 21:29 UTC, merged